package main

var english5k = []string{
	// Top 200
	"the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
	"it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
	"this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
	"or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
	"so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
	"when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
	"people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
	"than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
	"back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
	"even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
	"great", "between", "need", "large", "under", "never", "each", "right", "hand", "high",
	"place", "very", "through", "still", "long", "been", "same", "another", "much", "should",
	"last", "life", "state", "since", "world", "house", "keep", "might", "while", "found",
	"own", "part", "old", "home", "small", "end", "put", "help", "here", "show",
	"every", "big", "name", "number", "group", "ask", "such", "turn", "few", "run",
	"move", "must", "tell", "point", "city", "play", "live", "find", "head", "where",
	"those", "may", "down", "side", "change", "line", "set", "act", "try", "around",
	"close", "night", "real", "left", "open", "seem", "next", "walk", "begin", "both",
	"school", "child", "grow", "country", "more", "many", "did", "man", "woman", "said",
	"too", "does", "made", "let", "off", "had", "before", "call", "being", "thing",
	// 200-500
	"though", "start", "against", "talk", "story", "far", "hard", "really", "eye",
	"door", "always", "water", "face", "light", "government", "power", "room",
	"mother", "area", "money", "again", "later", "already", "done", "enough", "almost",
	"above", "once", "family", "leave", "body", "young", "book", "game", "example",
	"company", "answer", "system", "three", "himself", "air", "different", "picture", "during",
	"away", "course", "quite", "order", "second", "service", "problem", "children",
	"possible", "often", "early", "idea", "least", "word", "father", "among", "form",
	"program", "heard", "question", "white", "hold", "stand", "until", "street", "plan",
	"together", "within", "gone", "whether", "behind", "without", "result", "along",
	"car", "land", "report", "case", "perhaps", "age", "several", "nothing",
	"fact", "half", "history", "morning", "reason", "became", "given",
	"general", "social", "others", "sure", "kind", "certain", "local", "interest",
	"party", "present", "human", "bring", "true", "war", "full", "office", "read",
	// 500-1000
	"study", "sense", "court", "level", "class", "development", "person", "market",
	"known", "field", "lot", "national", "whole", "short", "process",
	"voice", "include", "important", "student", "rather",
	"become", "return", "mean", "million", "information",
	"society", "authority", "moment", "girl", "today", "figure", "provide", "political",
	"toward", "view", "best", "minute", "continue", "clear", "table", "force",
	"actually", "third", "education", "month", "control", "type", "industry",
	"write", "rate", "food", "period", "four", "building", "available", "meet", "community",
	"public", "finally", "remember", "position", "ago", "policy", "deal", "especially",
	"ground", "effect", "effort", "piece", "red", "increase", "produce",
	"research", "action", "paper", "economic", "five", "wife", "usually",
	"support", "role", "strong", "heart", "simply", "data",
	"reach", "break", "happen", "growth", "tax", "south", "death",
	"experience", "watch", "appear", "region", "president", "pay", "less", "church",
	"understand", "trade", "friend", "low", "cost", "oil", "price", "pass",
	"value", "near", "international", "learn", "property", "window", "natural", "drive",
	"arm", "issue", "wall", "player", "stage", "center", "cut", "nor", "hot",
	"design", "draw", "choose", "create", "cause", "hope", "join", "teach", "drop",
	"develop", "able", "news", "defense", "bed", "themselves", "black", "serve", "tree",
	"material", "technology", "catch", "step", "baby", "computer", "film", "popular",
	"free", "director", "happy", "top", "summer", "event", "wonder", "final", "record",
	"concern", "size", "accept", "six", "amount", "staff", "sell", "chance", "garden",
	"doctor", "production", "security", "hundred", "future", "either", "agree", "sound",
	"wrong", "past", "recent", "carry", "north", "team", "pull", "fall", "raise",
	"consider", "rest", "west", "attention", "space", "remain", "across", "beat",
	"blood", "hair", "entire", "mark", "season", "machine", "sing", "foot", "press",
	"beautiful", "charge", "front", "risk", "image", "animal", "source", "enter",
	"cover", "common", "training", "ball", "music", "practice", "quickly", "dark",
	"cold", "star", "color", "response", "blue", "campaign", "miss", "nation",
	// 1000-2000
	"relationship", "town", "century", "store", "sign", "suddenly", "letter", "seven",
	"firm", "born", "feeling", "base", "central", "activity", "likely", "count",
	"manage", "corner", "measure", "challenge", "wide", "bit", "approach", "project",
	"movement", "fish", "sea", "account", "explain", "floor", "cell",
	"fail", "board", "reduce", "single", "brother", "page", "model", "shape",
	"rule", "deep", "heat", "section", "husband", "skill", "green",
	"range", "memory", "contain", "spend", "stock", "apply",
	"sister", "leader", "agreement", "condition", "foreign", "scene", "glass", "dog",
	"hospital", "seat", "stay", "health", "test", "date", "trouble", "eight",
	"unit", "evidence", "laugh", "shot", "direction", "exist",
	"brown", "various", "save", "claim", "majority", "sit", "standard", "hotel",
	"decision", "wind", "protect", "media", "weapon", "resource", "indicate", "safe",
	"operation", "focus", "interview", "success", "enjoy", "imagine", "share", "loss",
	"finger", "speech", "outside", "painting", "professor", "bag", "race", "crime",
	"fill", "huge", "whatever", "remove", "individual", "surface", "basic",
	"realize", "observe", "prove", "note", "represent", "economy", "goal", "bank",
	"pain", "current", "manager", "travel", "discussion", "east",
	"list", "reveal", "poor", "teacher", "horse", "middle", "mountain", "civil",
	"task", "demand", "kitchen", "agency", "edge", "phone", "employee", "reality",
	"partner", "perfect", "ten", "fight", "exchange", "radio", "fly",
	"artist", "opinion", "variety", "attack", "gun", "shake", "statement",
	"village", "certainly", "collection", "finish", "ahead", "wear", "budget",
	"worry", "officer", "serious", "wish", "generation", "candidate", "tough",
	"physical", "lie", "key", "smile", "trip", "software", "democratic", "network",
	"conference", "truth", "regular", "weight", "rich", "effective",
	"benefit", "performance", "bill", "message", "suggest",
	"express", "capital", "culture", "treat", "dinner", "prepare", "option", "fast",
	"feature", "avoid", "consumer", "maintain", "limited", "establish",
	"version", "prevent", "soldier", "financial", "commission", "heavy", "thought",
	"tonight", "strange", "commercial", "recently", "mass", "reform", "supply",
	"collect", "hang", "scientist", "argument", "determine", "lift", "tomorrow",
	"strategy", "tiny", "throw", "spread", "contrast", "profit", "district",
	"confirm", "somewhat", "tradition", "capture", "divide", "critic", "distance",
	"neighbor", "deny", "react", "target", "proposal", "deliver", "critic",
	"promise", "survive", "expand", "intention", "engage", "literary", "approve",
	"graduate", "negotiate", "credit", "organize", "display", "urban", "enable",
	"initiative", "minority", "dramatic", "mental", "strike", "launch", "contribute",
	"invest", "household", "session", "distinction", "framework", "estimate", "fiction",
	"abandon", "scholar", "legislation", "participate", "assumption", "dispute",
	// 2000-3500
	"phenomenon", "remarkable", "investigate", "intellectual", "contemporary", "oppose",
	"restore", "extraordinary", "inevitable", "criticism", "accompany",
	"priority", "preserve", "transform", "evolve", "inevitable", "perceive",
	"constitute", "paragraph", "anticipate", "dominant", "acquisition",
	"ceremony", "accommodate", "reluctant", "negotiate", "paragraph", "accumulate",
	"restrict", "fundamental", "dramatic", "elaborate", "explicit",
	"frustrate", "demonstrate", "comprehensive", "legitimate", "guarantee",
	"enthusiasm", "sophisticated", "convenient", "controversy", "emphasize",
	"accomplish", "vulnerable", "inevitable", "phenomenon", "contemporary",
	"enthusiasm", "exaggerate", "ingredient", "significance", "perception",
	"consensus", "equivalent", "hierarchy", "implement", "interpret",
	"infrastructure", "nonetheless", "substitute", "supplement", "predominantly",
	"contradict", "undermine", "specification", "coherent", "incorporate",
	"inherent", "notorious", "unprecedented", "ambiguous", "commodity",
	"compromise", "consolidate", "contemplate", "depress", "deteriorate",
	"diminish", "disposition", "distinction", "draft", "duration",
	"eligible", "eliminate", "embrace", "encounter", "enforce",
	"enhance", "enterprise", "equation", "facilitate", "format",
	"formula", "foundation", "fragment", "generate", "genre",
	"guideline", "illustrate", "impulse", "incentive", "incline",
	"inevitable", "inhibit", "initiate", "innovation", "inspect",
	"instance", "integral", "integrate", "integrity", "interval",
	"isolate", "justify", "label", "landscape", "layer",
	"likewise", "logic", "manipulate", "mature", "mechanism",
	"medium", "migrate", "minimal", "modify", "monitor",
	"mutual", "neutral", "norm", "notion", "nuclear",
	"occupy", "offset", "ongoing", "orient", "outcome",
	"overlap", "overseas", "panel", "passive", "persist",
	"perspective", "phase", "portion", "pose", "precise",
	"preliminary", "presume", "principal", "profile", "prohibit",
	"promote", "proportion", "prospect", "protocol", "pursue",
	"radical", "random", "ratio", "rational", "regime",
	"reinforce", "relevant", "reluctance", "resolve", "revise",
	"revolution", "rhetoric", "rigid", "route", "scenario",
	"scheme", "scope", "sequence", "shelter", "shift",
	"simulate", "sole", "somewhat", "specify", "sphere",
	"stable", "statistic", "straightforward", "submit", "subordinate",
	"subsequent", "sustain", "symbol", "tape", "terminate",
	"theme", "thereby", "thesis", "trace", "transit",
	"trigger", "ultimate", "undergo", "undertake", "unify",
	"utilize", "valid", "vary", "vehicle", "virtual",
	"visible", "volume", "voluntary", "welfare", "widespread",
	// 3500-5000
	"abstract", "academy", "accessible", "acute", "adjacent",
	"adolescent", "advocate", "aesthetic", "aggregate", "allocate",
	"ambassador", "analogy", "annual", "apparatus", "appendix",
	"appetite", "arbitrary", "archive", "arena", "assert",
	"authentic", "authorize", "auto", "backdrop", "benchmark",
	"bias", "binary", "biography", "blend", "blueprint",
	"bonus", "breach", "bureau", "calendar", "catalog",
	"cease", "charter", "chronic", "circulate", "civic",
	"clarity", "cluster", "coalition", "cognitive", "coincide",
	"collapse", "colonial", "compact", "compatible", "compel",
	"compile", "complement", "comply", "conceive", "confine",
	"confuse", "conscience", "consecutive", "consent", "console",
	"conspire", "constraint", "consult", "contempt", "contend",
	"context", "converge", "conversion", "convey", "cooperate",
	"coordinate", "copper", "corporate", "correlate", "correspond",
	"counter", "courtesy", "craft", "credible", "creed",
	"cuisine", "cumulative", "currency", "curriculum", "customs",
	"database", "deadline", "debris", "debut", "decline",
	"dedicate", "default", "deficit", "delicate", "denial",
	"dense", "deploy", "deprive", "descend", "designate",
	"desktop", "detain", "devote", "diagnose", "digital",
	"dilemma", "diploma", "disclose", "discourse", "discrete",
	"disorder", "displace", "doctrine", "domain", "domestic",
	"donate", "dose", "drought", "dual", "dynamic",
	"echo", "ecology", "editorial", "ego", "elaborate",
	"electoral", "eligible", "embassy", "emission", "empirical",
	"empower", "enact", "encompass", "endorse", "enforce",
	"engineer", "enrich", "enroll", "ensue", "entity",
	"entropy", "envelope", "equity", "erode", "essence",
	"eternal", "ethnic", "evacuate", "evaluate", "evident",
	"evoke", "evolve", "exceed", "exclude", "execute",
	"exempt", "exile", "exotic", "explicit", "exploit",
	"export", "extract", "fabric", "faction", "faculty",
	"fantasy", "fare", "fatal", "favorable", "feedback",
	"feminine", "fertile", "fiber", "fierce", "fiscal",
	"flaw", "fleet", "flexible", "flourish", "fluid",
	"forecast", "forge", "formula", "forth", "foster",
	"fraction", "franchise", "frontier", "frost", "fulfill",
	"fund", "fusion", "galaxy", "gaze", "genetic",
	"genius", "gesture", "ghost", "glimpse", "globe",
	"grace", "gradual", "grain", "graphic", "gratitude",
	"gravity", "grief", "grim", "grip", "gross",
	"habitat", "halt", "harbor", "harmony", "harsh",
	"harvest", "haunt", "hazard", "heritage", "hollow",
	"horizon", "hostile", "humble", "hybrid", "hypothesis",
	"ideology", "illusion", "immune", "implicit", "import",
	"impose", "impulse", "incidence", "incorporate", "index",
	"indigenous", "induce", "infant", "inflict", "inform",
	"inhabit", "inject", "inner", "input", "insight",
	"inspect", "install", "instinct", "intact", "intense",
	"interfere", "interim", "interpret", "intervene", "intimate",
	"intrinsic", "invade", "invoke", "irony", "isolate",
	"junction", "jurisdiction", "keen", "kinetic", "kingdom",
	"ladder", "lag", "latitude", "launch", "layout",
	"legacy", "legend", "leisure", "lens", "liable",
	"liberal", "liberty", "linguistic", "linger", "literacy",
	"lobby", "loft", "longitude", "loop", "loyal",
	"lunar", "luxury", "magnetic", "magnitude", "mainstream",
	"mandate", "manifest", "manual", "margin", "marine",
	"marvel", "masculine", "meadow", "medieval", "memoir",
	"mentor", "mercy", "merely", "merit", "mesh",
	"metaphor", "metric", "midst", "militia", "mineral",
	"miniature", "miracle", "mode", "moderate", "molecule",
	"momentum", "monarch", "monopoly", "moral", "mortgage",
	"motive", "municipal", "muscle", "mutual", "mystery",
	"myth", "narrative", "naval", "navigate", "neglect",
	"noble", "nominate", "notable", "novel", "nucleus",
	"nutrition", "objective", "oblige", "obscure", "obstacle",
	"optic", "optimism", "oracle", "orbit", "organic",
	"orient", "orthodox", "outline", "output", "overcome",
	"overlook", "owe", "oxygen", "parade", "paradox",
	"parallel", "parish", "passive", "patent", "patron",
	"pause", "peak", "peasant", "peculiar", "penalty",
	"penetrate", "pension", "perceive", "peripheral", "permanent",
	"permit", "persist", "petition", "pilgrim", "pioneer",
	"pitch", "plead", "pledge", "plunge", "pole",
	"portfolio", "portrait", "postwar", "potent", "pottery",
	"poultry", "preach", "precede", "precious", "predator",
	"predict", "prejudice", "premier", "premise", "premium",
	"prescribe", "prestige", "prevalent", "primitive", "privilege",
	"probe", "proceed", "proclaim", "profound", "prohibit",
	"projection", "prominent", "prone", "propaganda", "propel",
	"prophet", "prosecute", "province", "provoke", "prudent",
	"pulse", "pump", "punish", "pupil", "puzzle",
	"quota", "realm", "rebel", "recession", "reckon",
	"reconcile", "recruit", "referendum", "reform", "refuge",
	"reign", "relay", "reliance", "remedy", "render",
	"renew", "renowned", "repeal", "replica", "republic",
	"resemble", "reside", "resign", "resort", "restrain",
	"retail", "retain", "retreat", "revenge", "revenue",
	"reverse", "revive", "revolt", "rhythm", "rival",
	"robust", "romance", "rotate", "ruling", "rumor",
	"rural", "sacrifice", "saint", "sanction", "satellite",
	"savage", "scandal", "scatter", "secular", "segment",
	"seize", "seminar", "sentiment", "serial", "sermon",
	"severe", "shallow", "siege", "skeptic", "slogan",
	"soar", "solar", "solidarity", "sovereign", "span",
	"spatial", "spectrum", "spiral", "sponsor", "squad",
	"stake", "stance", "staple", "stark", "statue",
	"steep", "stem", "stereotype", "stimulus", "strand",
	"strip", "strive", "stroke", "structure", "stumble",
	"suburban", "successor", "sue", "summit", "superb",
	"surplus", "surrender", "suspend", "sustain", "swear",
	"swift", "symbol", "syndrome", "tactic", "tailor",
	"talent", "tank", "taxpayer", "temple", "temporary",
	"tenant", "tender", "tenure", "terrain", "textile",
	"texture", "theology", "therapy", "thermal", "threshold",
	"thrive", "timber", "tissue", "toll", "torch",
	"tournament", "toxic", "trait", "transcript", "transmit",
	"transplant", "tribe", "tribute", "tropical", "tunnel",
	"turnover", "tutor", "twilight", "twist", "tyranny",
	"unanimous", "underline", "undertake", "unfold", "union",
	"unique", "unity", "unprecedented", "upgrade", "uphold",
	"uproar", "usage", "utmost", "vaccine", "valid",
	"vanish", "variable", "vendor", "venture", "verdict",
	"verse", "veteran", "viable", "vibrant", "vigor",
	"violate", "virtue", "vivid", "vocal", "volatile",
	"vow", "voyage", "vulnerable", "wage", "warrant",
	"weave", "wield", "wilderness", "withdraw", "witness",
	"worship", "worthy", "wrath", "yield", "zone",
}
