package main

var english1k = []string{
	"the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
	"it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
	"this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
	"or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
	"so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
	"when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
	"people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
	"than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
	"back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
	"even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
	"great", "between", "need", "large", "under", "never", "each", "right", "hand", "high",
	"place", "very", "through", "still", "long", "been", "same", "another", "much", "should",
	"last", "life", "state", "since", "world", "house", "keep", "might", "while", "found",
	"own", "part", "old", "home", "small", "end", "put", "help", "here", "show",
	"every", "big", "name", "number", "group", "ask", "such", "turn", "few", "run",
	"move", "must", "tell", "point", "city", "play", "live", "find", "head", "where",
	"those", "may", "down", "side", "change", "line", "set", "act", "try", "around",
	"close", "night", "real", "left", "open", "seem", "next", "walk", "begin", "both",
	"school", "child", "grow", "country", "more", "many", "did", "man", "woman", "said",
	"too", "does", "made", "let", "off", "had", "before", "call", "being", "thing",
	"though", "start", "might", "against", "talk", "story", "far", "hard", "really", "eye",
	"door", "between", "always", "water", "face", "light", "government", "power", "room",
	"mother", "area", "money", "again", "later", "already", "done", "enough", "almost",
	"above", "once", "family", "leave", "body", "young", "book", "game", "example",
	"company", "answer", "system", "three", "himself", "air", "different", "picture", "during",
	"number", "away", "course", "quite", "order", "second", "service", "problem", "children",
	"possible", "often", "early", "idea", "least", "word", "father", "among", "form",
	"program", "heard", "question", "white", "hold", "stand", "until", "street", "plan",
	"together", "within", "gone", "whether", "behind", "without", "result", "along",
	"car", "land", "point", "report", "case", "perhaps", "age", "several", "nothing",
	"fact", "half", "history", "woman", "morning", "reason", "became", "later", "given",
	"general", "high", "social", "others", "sure", "kind", "certain", "local", "interest",
	"party", "present", "human", "bring", "true", "war", "full", "office", "read",
	"study", "sense", "court", "level", "class", "development", "person", "market",
	"above", "known", "field", "lot", "national", "whole", "short", "already", "process",
	"door", "whose", "voice", "include", "power", "often", "important", "student", "rather",
	"become", "return", "seem", "mean", "million", "information", "question", "home", "area",
	"society", "authority", "moment", "girl", "today", "figure", "provide", "political",
	"toward", "view", "best", "minute", "continue", "clear", "table", "need", "force",
	"actually", "third", "least", "education", "month", "control", "type", "industry",
	"write", "rate", "food", "period", "four", "building", "available", "meet", "community",
	"public", "finally", "remember", "position", "ago", "policy", "deal", "especially",
	"close", "night", "ground", "effect", "effort", "piece", "red", "increase", "produce",
	"research", "action", "paper", "economic", "five", "history", "wife", "usually",
	"support", "role", "strong", "possible", "heart", "real", "simply", "data", "behind",
	"reach", "break", "half", "city", "happen", "growth", "tax", "south", "death",
	"experience", "watch", "appear", "region", "president", "pay", "less", "church",
	"understand", "trade", "usually", "friend", "low", "cost", "oil", "price", "pass",
	"value", "near", "international", "learn", "property", "window", "natural", "drive",
	"arm", "issue", "wall", "player", "stage", "center", "cut", "nor", "hot",
	"design", "draw", "choose", "create", "cause", "hope", "join", "teach", "drop",
	"develop", "able", "news", "defense", "bed", "themselves", "black", "serve", "tree",
	"material", "technology", "catch", "step", "baby", "computer", "film", "popular",
	"free", "director", "happy", "top", "summer", "event", "wonder", "final", "record",
	"concern", "size", "accept", "six", "amount", "staff", "sell", "chance", "garden",
	"doctor", "production", "security", "hundred", "future", "either", "agree", "sound",
	"wrong", "past", "recent", "carry", "north", "team", "pull", "fall", "raise",
	"consider", "rest", "west", "attention", "space", "remain", "across", "beat",
	"blood", "hair", "entire", "mark", "season", "machine", "sing", "foot", "press",
	"beautiful", "charge", "front", "risk", "image", "animal", "source", "table", "enter",
	"cover", "common", "training", "ball", "music", "practice", "quickly", "dark",
	"cold", "star", "color", "response", "blue", "campaign", "miss", "nation",
	"relationship", "town", "century", "store", "sign", "suddenly", "letter", "seven",
	"firm", "born", "feeling", "base", "central", "activity", "likely", "count",
	"manage", "corner", "measure", "challenge", "wide", "bit", "approach", "project",
	"movement", "material", "fish", "sea", "account", "explain", "floor", "cell",
	"fail", "board", "reduce", "single", "brother", "page", "model", "shape",
	"rule", "deep", "past", "heat", "section", "husband", "skill", "green", "hold",
	"range", "memory", "attention", "contain", "whose", "spend", "stock", "apply",
	"sister", "leader", "agreement", "condition", "foreign", "scene", "glass", "dog",
	"hospital", "seat", "stay", "health", "test", "date", "trouble", "eight",
	"unit", "evidence", "laugh", "miss", "shot", "direction", "exist", "bit",
	"brown", "various", "save", "claim", "majority", "sit", "standard", "hotel",
	"decision", "wind", "protect", "media", "weapon", "resource", "indicate", "safe",
	"operation", "focus", "interview", "success", "enjoy", "imagine", "share", "loss",
	"finger", "speech", "outside", "painting", "professor", "bag", "race", "crime",
	"fill", "huge", "whatever", "remove", "plan", "individual", "surface", "basic",
	"realize", "observe", "prove", "note", "represent", "economy", "goal", "bank",
	"pain", "current", "manager", "oil", "travel", "discussion", "east", "note",
	"list", "reveal", "poor", "teacher", "horse", "middle", "mountain", "civil",
	"task", "demand", "kitchen", "agency", "edge", "phone", "employee", "reality",
	"partner", "perfect", "ten", "fight", "exchange", "finally", "radio", "fly",
	"artist", "opinion", "price", "variety", "attack", "gun", "shake", "statement",
	"village", "certainly", "collection", "finish", "ahead", "wear", "budget",
	"worry", "officer", "serious", "wish", "generation", "candidate", "tough",
	"physical", "lie", "key", "smile", "trip", "software", "democratic", "network",
	"conference", "born", "truth", "regular", "weight", "rich", "effective",
	"benefit", "performance", "bill", "message", "serious", "suggest", "church",
	"express", "capital", "culture", "treat", "dinner", "prepare", "option", "fast",
	"feature", "avoid", "consumer", "crime", "maintain", "limited", "establish",
	"version", "prevent", "soldier", "financial", "commission", "heavy", "thought",
	"tonight", "strange", "commercial", "recently", "mass", "reform", "supply",
}
